services:
  - type: web
    name: n8n-free
    env: docker
    plan: free

    envVars:
      - key: N8N_HOST
        value: n8n-free.onrender.com

      - key: N8N_PORT
        value: 5678

      - key: N8N_PROTOCOL
        value: https

      - key: WEBHOOK_URL
        value: https://n8n-free.onrender.com/

      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata

      - key: EXECUTIONS_PROCESS
        value: main

      - key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
        value: none

      - key: EXECUTIONS_DATA_SAVE_ON_ERROR
        value: all

      - key: EXECUTIONS_DATA_PRUNE
        value: true

      - key: EXECUTIONS_DATA_MAX_AGE
        value: 24

      - key: N8N_DIAGNOSTICS_ENABLED
        value: false

      - key: N8N_VERSION_NOTIFICATIONS_ENABLED
        value: false

      - key: DB_SQLITE_POOL_SIZE
        value: 1
